/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package discord_board_5;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author RYAN
 */
public class MainBoard extends javax.swing.JFrame {

    /**
     * Creates new form MainBoard1
     */
    public MainBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    public void initComponents() {
    	Connection con = null;
    	Statement st = null; 
    	 ResultSet rs = null; String s;


    	//DB 연결 

    	try{ con = DriverManager.getConnection("jdbc:mysql://seulgi94.mooo.com:3306/test", "root", "rhrnak34!");
    	 st = con.createStatement();
    	 s = "SELECT * FROM `recentscore` ORDER BY `recentscore`.`Position` ASC"; 
    	 rs = st.executeQuery(s);
    	 ResultSetMetaData rsmt = rs.getMetaData(); 
    	 
    	 /*
    	  * 테이블 DB에서 불러온후 JTable로 출력
    	  */
    	 int c = rsmt.getColumnCount();
    	 Vector column = new Vector(c);

    	 for(int i = 1; i <= c; i++) {
    	 column.add(rsmt.getColumnName(i)); 
    	 } 

    	 Vector data = new Vector(); 
    	 Vector row = new Vector(); 

    	 while(rs.next()) { 
    	 row = new Vector(c); 

    	 for(int i = 1; i <= c; i++){
    	 row.add(rs.getString(i)); 
    	 } 

    	 data.add(row); 
    	 }
         jTable1  = new javax.swing.JTable(data,column);
         
    	}catch(Exception e){ JOptionPane.showMessageDialog(null, "ERROR"); }
    	 finally{
    	  try{ st.close(); 
    	  rs.close(); 
    	  con.close(); 
    	  }
    	 catch(Exception e) { JOptionPane.showMessageDialog(null, "ERROR CLOSE"); 
    	  
    	 }
    	 }
 

    	
    
    

    	  
    	 
    	 
        jB_LogOut = new javax.swing.JButton();
        jLabel_Nick = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel_Title = new javax.swing.JLabel();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_LogOut.setText("Log-Out");
        jB_LogOut.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();

		        client_frame chat = new client_frame();
		        chat.setVisible(false);
		        chat.dispose();


			}
		});
        jLabel_Title.setFont(new java.awt.Font("Gulim", 0, 24)); // NOI18N
        jLabel_Title.setText("2018 잉글랜드 프리미어리그 34라운드 순위");
        jLabel_Nick.setFont(new Font("Dialog", Font.PLAIN, 17)); // NOI18N
        jLabel_Nick.setText("'" + MainFrame_Second.a +"'" + " 님 환영 합니다");

           
        jScrollPane2.setViewportView(jTable1);
        
        JButton btnChatRoom = new JButton("Chat Room");
        btnChatRoom.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		client_frame chatting = new client_frame(); //여기가 프레임 전환 역할
		        chatting.setVisible(true);
        	}
        });
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(103)
        					.addComponent(jLabel_Title, GroupLayout.PREFERRED_SIZE, 485, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(25)
        					.addComponent(jLabel_Nick, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
        					.addComponent(btnChatRoom, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jB_LogOut, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 671, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(35)
        			.addComponent(jLabel_Title, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        			.addGap(32)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jB_LogOut)
        				.addComponent(btnChatRoom)
        				.addComponent(jLabel_Nick, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 531, GroupLayout.PREFERRED_SIZE)
        			.addGap(52))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    	
    	
    		
    	
    }// </editor-fold>                        
                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBoard().setVisible(true);
            }
        });
    }
    private javax.swing.JButton jB_LogOut;
    private javax.swing.JLabel jLabel_Nick;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
}
